name: geog696f_python311
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.6.2.post1=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h460d6c5_5
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=h5499902_0
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py311h3f08180_2
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.2=h7ab814d_0
  - ca-certificates=2024.8.30=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.24.0=py311h9cb3ce9_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - cftime=1.6.4=py311h0f07fe1_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py311h2c37856_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.7=py311h3f08180_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fonttools=4.54.1=py311h460d6c5_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - geos=3.13.0=hf9b8971_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.4=nompi_h99fbd1e_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.6=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.28.0=pyh707e725_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h267d04e_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py311h2c37856_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.1.3=hebf3989_0
  - libblas=3.9.0=24_osxarm64_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=24_osxarm64_openblas
  - libcurl=8.10.1=h13a7ad3_0
  - libcxx=19.1.1=ha82da77_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.6.3=hf9b8971_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=24_osxarm64_openblas
  - libnetcdf=4.9.2=nompi_h853a48d_115
  - libnghttp2=1.58.0=ha4dd798_1
  - libopenblas=0.3.27=openmp_h517c56d_1
  - libpng=1.6.44=hc14010f_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.46.1=hc14010f_0
  - libssh2=1.11.0=h7a5bd25_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h01dff8b_4
  - libzip=1.11.1=hfc4440f_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=19.1.1=hb52a8e5_1
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=3.0.1=py311h0ecf0c1_1
  - matplotlib=3.9.2=py311ha1ab1f8_1
  - matplotlib-base=3.9.2=py311hbe3227e_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h7bae524_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.7.1=nompi_py311h5dc35ae_103
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=2.1.2=py311h6de8079_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.2=h8359307_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py311h9cb3ce9_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py311hc903d1b_1
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - proj=9.5.0=h61a8e3e_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - psutil=6.0.0=py311hae2e1ce_2
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.3.1=py311h09e6bbd_1
  - pyobjc-framework-cocoa=10.3.1=py311h09e6bbd_1
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyproj=3.7.0=py311hb4b81e0_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.10=h739c21a_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h460d6c5_1
  - pyzmq=26.2.0=py311h730b646_3
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h92ec313_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py311h481aa64_1
  - scikit-learn=1.5.2=py311h9e23f0f_1
  - scipy=1.14.1=py311h2929bc6_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shapely=2.0.6=py311hac502b4_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=hd02b534_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.46.1=h3b4c4e4_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py311h0f07fe1_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py311h460d6c5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024b=hc8b5060_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - xarray=2024.9.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd74edd7_1
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=h9f5b81c_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py311ha60cc69_1
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - click==8.1.7
      - cloudpickle==3.1.0
      - dask==2024.9.1
      - erddapy==2.2.3
      - fsspec==2024.9.0
      - locket==1.0.0
      - partd==1.4.2
      - toolz==1.0.0
      - tqdm==4.66.5
      - xarray-datatree==0.0.14
      - xeofs==3.0.3
      - xlrd==2.0.1
prefix: /Users/kja/anaconda3/envs/geog696fpython311
